<?php
/***********************************************

Ad Randomizer system

Created by Nitemare
http://www.nitemare.ca

Release date: 16th September 2007

edited by: vintagedaddyo
http://community.mybb.com/user-6029.html

last edited: 10th March 2019

************************************************/


/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Nederlands
// Author of the language pack : Wageral
// Language pack translators website : https://www.wageral.nl/oriste/
// Compatible version of MyBB : 1820
// Last edited in MyBB Editor by : oriste
// Last edited date : Sun, 10 Mar 2019 08:35:17 +0000
// --------------------------------------------------------------------------------

$l['ads_PName'] = 'Ad Randomizer system';
$l['ads_PDesc'] = 'Dit systeem toont een banner aan de onderkant van het forum, en rouleert door een lijst van banners';
$l['ads_PWeb'] = 'http://community.mybb.com/user-6029.html';
$l['ads_PAuth'] = 'Nitemare & updated by Vintagedaddyo';
$l['ads_PAuthSite'] = 'http://community.mybb.com/user-6029.html';
$l['ads_PVer'] = '5.0.3';
$l['ads_PGUID'] = '80d9be40af59e71edb421b93e820b10f';
$l['ads_PCompat'] = '18*';
$l['ads_submenu_title'] = 'Ad Rotation Manager';
$l['ads_submenu_action_'] ='';
$l['ads_table_output'] = 'Ad Randomizer systeem: Instellingen';
$l['ads_table_output_add'] = 'Ad Randomizer system: Toevoegen';
$l['ads_table_output_edit'] = 'Ad Randomizer system: Aanpassen';
$l['ads_table_output_reset'] = 'Ad Randomizer system: Herstellen';
$l['ads_table_output_delete'] = 'Ad Randomizer system: Verwijderen';
$l['ads_add_breadcrumb'] = 'Ad Randomizer systeem';
$l['ads_add_header'] = 'Ad Randomizer Management systeem';
$l['ads_do_add_breadcrumb'] = 'Ad Randomizer systeem';
$l['ads_do_add_header'] = 'Ad Randomizer Management systeem';
$l['ads_do_add_flash_error_notice'] = 'Je dient de code voor de banner in te voeren';
$l['ads_do_add_flash_error'] = 'foutmelding';
$l['ads_do_add_flash_success_notice'] = 'Banner succesvol toegevoegd.';
$l['ads_do_add_flash_success'] = 'gelukt';
$l['ads_edit_breadcrumb'] = 'Ad Randomizer systeem';
$l['ads_edit_header'] = 'Ad Randomizer Management systeem';
$l['ads_edit_flash_error_notice'] = 'Selecteer eerst een banner om aan te passen';
$l['ads_edit_flash_error'] = 'foutmelding';
$l['ads_do_edit_breadcrumb'] = 'Ad Randomizer systeem';
$l['ads_do_edit_header'] = 'Ad Randomizer Management systeem';
$l['ads_do_edit_flash_code_error_notice'] = 'Voer de code van de banner in';
$l['ads_do_edit_flash_code_error'] = 'foutmelding';
$l['ads_do_edit_flash_success_title'] = 'Mededeling met ID:';
$l['ads_do_edit_flash_success_notice'] = 'succesvol aangepast.';
$l['ads_do_edit_flash_success'] = 'gelukt';
$l['ads_reset_breadcrumb'] = 'Ad Randomizer systeem';
$l['ads_reset_header'] = 'Reset aantal keer bekeken';
$l['ads_reset_flash_error_notice'] = 'Selecteer eerst een banner';
$l['ads_reset_flash_error'] = 'foutmelding';
$l['ads_reset_message'] = 'Weet je zeker dat je het aantal keer bekeken wilt resetten voor de banner met ID:';
$l['ads_reset_button_reset'] = 'Aantal keer bekeken gereset';
$l['ads_reset_button_cancel'] = 'Annuleren';
$l['ads_do_reset_flash_reset_success_title'] = 'Aantal keer bekenen banner met ID:';
$l['ads_do_reset_flash_reset_success_notice'] = ' resetten gelukt.';
$l['ads_do_reset_flash_reset_success'] = 'gelukt';
$l['ads_do_reset_flash_disable_success_title'] = 'Banner met ID:';
$l['ads_do_reset_flash_disable_success_notice'] = ' succesvol uitgezet.';
$l['ads_do_reset_flash_disable_success'] = 'gelukt';
$l['ads_do_reset_flash_mode_enable_success_title'] = 'Banner met ID:';
$l['ads_do_reset_flash_mode_enable_success_notice'] = ' succesvol aangezet.';
$l['ads_do_reset_flash_mode_enable_success'] = 'gelukt';
$l['ads_do_reset_flash_mode_disable_success_title'] = 'Banner met  ID:';
$l['ads_do_reset_flash_mode_disable_success_notice'] = '  succesvol uitgezet.';
$l['ads_do_reset_flash_mode_disable_success'] = 'gelukt';
$l['ads_delete_breadcrumb'] = 'Ad Randomizer systeem';
$l['ads_delete_header'] = 'Ad Randomizer Management systeem';
$l['ads_delete_flash_error_notice'] = 'Selecteer eerst een banner';
$l['ads_delete_flash_error'] = 'foutmelding';
$l['ads_delete_header_alert'] = 'Verwijder Alert';
$l['ads_delete_message'] = 'Weet je zeker dat je de de banner wilt verwijderen met ID: ';
$l['ads_delete_button_delete'] = 'Verwijder';
$l['ads_delete_button_cancel'] = 'Annuleer';
$l['ads_do_delete_breadcrumb'] = 'Ad Randomizer systeem';
$l['ads_do_delete_header'] = 'Ad Randomizer Management systeem';
$l['ads_do_delete_flash_success_title'] = 'Banner met  ID:';
$l['ads_do_delete_flash_success_notice'] = ' succesvol verwijderd.';
$l['ads_do_delete_flash_success'] = 'gelukt';
$l['ads_do_delete_current_ads'] = 'Huidige banners';
$l['ads_do_delete_add_id'] = 'Banner ID';
$l['ads_do_delete_ad'] = 'Toevoegen';
$l['ads_do_delete_mode'] = 'Instelling';
$l['ads_do_delete_number_views'] = 'Aantal keer bekeken';
$l['ads_do_delete_max_views'] = 'Max aantal te bekijken';
$l['ads_mode_infinite'] = 'Onbeperkt';
$l['ads_mode_limited'] = 'Beperkt';
$l['ads_mode_disabled'] = 'Uitgeschakeld';
$l['ads_mode_expired'] = 'Verlopen';
$l['ads_mode_error'] = 'Foutmelding!';
$l['ads_button_add'] = 'Toevoegen';
$l['ads_button_edit'] = 'Aanpassen';
$l['ads_button_disable_enable'] = 'Uitschakelen/Inschakelen';
$l['ads_button_reset_view'] = 'Reset aantal';
$l['ads_button_delete'] = 'Verwijder';
$l['ads_image_path_full'] = 'http://script voor de banner';
$l['ads_add_advertisement'] = 'Roulerende banners';
$l['ads_add_advertisement_message'] = 'Maximum aantal views voordat banner wordt verwijderd (0 voor oneindig)<br />';
$l['ads_add_advertisement_add_button'] = 'Toevoegen';
$l['ads_add_advertisement_reset_button'] = 'Reset';
$l['ads_edit_advertisement'] = 'Banner aanpassen';
$l['ads_edit_advertisement_message'] = 'Maximum aantal views voordat banner wordt verwijderd (0 voor oneindig)<br />';
$l['ads_edit_advertisement_edit_button'] = 'Aanpassen';
$l['ads_edit_advertisement_reset_button'] = 'Reset';

?>
